
name: DevSecOps Automated Security Gate

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  security-scan:
    name: Execute Pipeline Audits
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install Project Dependencies
      run: npm ci

    # We download the GitLeaks binary and run it manually just like local!
    - name: Run GitLeaks (Secret Scanner)
      run: |
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
        tar -xzf gitleaks_8.24.3_linux_x64.tar.gz
        ./gitleaks detect --source=. --verbose --no-git

    # We use pipx to get the absolute newest Semgrep version, preventing the crash!
    - name: Run Semgrep (SAST Engine)
      run: |
        pipx install semgrep
        semgrep scan --config=auto .

    - name: Run Dependency Audit (SCA)
      run: npm audit --audit-level=high
